version: "3"

services:
  web:
    build: .
    ports:
      - "8888:80"
      - "2222:22"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/weather-transfer-files.conf"
      - "weather-files-data:/usr/share/nginx/data"
    # depends-on:
    #   - 'ftp'
  ftp:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "weather-files-data:/home/ftpusers/"
      - "./ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftpusers
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/ftpusers
    restart: unless-stopped

volumes:
  weather-files-data:
